// LitematicaQL: Quick Look preview for Minecraft schematics on macOS.
// Copyright (c) 2026 4rcadia
// SPDX-License-Identifier: MIT

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vite-plus/test";
import {
  decodeSchematic,
  displayNameForFileName,
  formatForFileName,
  prepareSchematicBytes,
  schematicFormats,
  supportedFileExtensionList,
  type SchematicFormat,
} from "./schematic-formats";
import { SchematicFormatError } from "./schematic-limits";

/** Reads a fixture or demo, named relative to the repository's Fixtures directory. */
function read(relativePath: string): Uint8Array {
  return new Uint8Array(readFileSync(new URL(`../../Fixtures/${relativePath}`, import.meta.url)));
}

function fixture(name: string): Uint8Array {
  return read(`Formats/${name}`);
}

/**
 * Every extension the app registers, with the demo it bundles for that
 * file format. The demos are generated by `scripts/generate-demos.mjs`, so this
 * table doubles as the check that the app's bundled gallery actually decodes —
 * a demo that stops loading fails here rather than in the app.
 */
const cases: { extension: string; file: string; format: SchematicFormat; blocks: number }[] = [
  { extension: "litematic", file: "Demos/Cottage.litematic", format: "litematic", blocks: 600 },
  { extension: "schem", file: "Demos/Archway.schem", format: "sponge", blocks: 469 },
  { extension: "schematic", file: "Demos/Watchtower.schematic", format: "classic", blocks: 598 },
  { extension: "nbt", file: "Formats/Structure.nbt", format: "structure", blocks: 2 },
  { extension: "snbt", file: "Demos/Bridge.snbt", format: "snbt", blocks: 314 },
  { extension: "mcstructure", file: "Demos/Pyramid.mcstructure", format: "bedrock", blocks: 697 },
  { extension: "nusn", file: "Demos/Garden.nusn", format: "snapshot", blocks: 239 },
];

/**
 * Every demo the app bundles, which the gallery shows in this order. Each is a
 * different model, so this also guards the gallery against a card that points
 * at a file the generator no longer produces.
 */
const demoFiles = [
  "Cottage.litematic",
  "Archway.schem",
  "Watchtower.schematic",
  "Bloom.nbt",
  "Bridge.snbt",
  "Pyramid.mcstructure",
  "Garden.nusn",
];

describe("schematic formats", () => {
  it("maps every registered extension", () => {
    for (const { extension, format } of cases) {
      expect(formatForFileName(`schematic.${extension}`), extension).toBe(format);
    }
    expect(Object.keys(schematicFormats)).toHaveLength(cases.length);
  });

  it("maps extensions without regard to case", () => {
    for (const { extension, format } of cases) {
      expect(formatForFileName(`SCHEMATIC.${extension.toUpperCase()}`), extension).toBe(format);
    }
  });

  it("returns undefined when there is no extension to read", () => {
    expect(formatForFileName("schematic")).toBeUndefined();
    expect(formatForFileName("schematic.")).toBeUndefined();
    expect(formatForFileName("archive.schematic.txt")).toBeUndefined();
    expect(formatForFileName(".litematic")).toBeUndefined();
  });

  it("reads the last extension of a dotted file name", () => {
    expect(formatForFileName("my.base.v2.schem")).toBe("sponge");
  });

  it("titles a file without its extension", () => {
    expect(displayNameForFileName("my.base.v2.schem")).toBe("my.base.v2");
    expect(displayNameForFileName(".litematic")).toBe(".litematic");
    expect(displayNameForFileName("schematic")).toBe("schematic");
  });

  it("names every supported extension in the rejection message", () => {
    for (const { extension } of cases) {
      expect(supportedFileExtensionList).toContain(`.${extension}`);
    }
  });

  it("decodes every registered format within budget", () => {
    for (const { file, format, blocks } of cases) {
      const schematic = decodeSchematic(format, read(file));

      expect(schematic.blockCount(), file).toBe(blocks);
    }
  });

  it("bundles one demo per registered file format", () => {
    const formats = demoFiles.map((file) => formatForFileName(file));

    expect(demoFiles).toHaveLength(cases.length);
    const byName = (left: string | undefined, right: string | undefined) =>
      (left ?? "").localeCompare(right ?? "");

    expect([...formats].sort(byName)).toEqual(cases.map(({ format }) => format).sort(byName));
  });

  it("decodes every bundled demo", () => {
    for (const file of demoFiles) {
      const format = formatForFileName(file);
      if (!format) {
        throw new Error(`Bundled demo has no registered format: ${file}`);
      }

      const schematic = decodeSchematic(format, read(`Demos/${file}`));
      const dimensions = schematic.dimensions();

      // A demo that decodes to nothing would render as an empty preview, which
      // is the one failure a gallery card cannot show.
      expect(schematic.blockCount(), file).toBeGreaterThan(0);
      expect(
        [dimensions.x, dimensions.y, dimensions.z].every((axis) => axis > 0),
        file,
      ).toBe(true);
    }
  });

  it("decodes the same bytes the same way regardless of the file name's case", () => {
    const bytes = fixture("Classic.schematic");

    expect(formatForFileName("A.SCHEMATIC")).toBe("classic");
    expect(decodeSchematic("classic", bytes).blockCount()).toBe(7);
  });

  it("reads a bundled litematic rather than only the fixture", () => {
    const schematic = decodeSchematic("litematic", read("Demos/Cottage.litematic"));

    expect(schematic.getBlockString(0, 0, 0)).toBe("minecraft:stone_bricks");
  });

  it("reads a structure through its converted text, not its original bytes", () => {
    const bytes = fixture("Structure.nbt");

    expect(prepareSchematicBytes("structure", bytes)).not.toBe(bytes);
    expect(decodeSchematic("structure", bytes).getBlockString(0, 0, 0)).toBe(
      "minecraft:oak_log[axis=y]",
    );
  });

  it("recovers a brace-spelled .snbt through the normalization retry", () => {
    const bytes = fixture("Structure.snbt");

    expect(decodeSchematic("snbt", bytes).getBlockString(0, 0, 0)).toBe(
      "minecraft:oak_log[axis=y]",
    );
  });

  it("reports unreadable bytes as unreadable rather than as a limit", () => {
    const nonsense = new TextEncoder().encode("this is not a schematic");

    expect(() => decodeSchematic("litematic", nonsense)).toThrow(SchematicFormatError);
    expect(() => decodeSchematic("litematic", nonsense)).toThrow(
      /not a readable Minecraft schematic/u,
    );
  });

  it("reports a snbt file that stays broken after normalization", () => {
    const nonsense = new TextEncoder().encode("{DataVersion:3953}");

    expect(() => decodeSchematic("snbt", nonsense)).toThrow(SchematicFormatError);
  });
});
